### ISSUE TITLE
Error when send message

### ISSUE THREAD

**Issue by neutrino-01** [tax/pywhatsapp#13]
shubham@shubham-Vostro-2520:~/Desktop/tg/yowsup$ python3 send.py
Traceback (most recent call last):
  File "send.py", line 4, in <module>
    client.send_message(phone_to,"hello")
  File "/home/shubham/Desktop/tg/tg/lib/python3.5/site-packages/whatsapp.py", line 153, in send_message
    self._send_message(to, message)
  File "/home/shubham/Desktop/tg/tg/lib/python3.5/site-packages/whatsapp.py", line 148, in _send_message
    self.stack.loop()
  File "/home/shubham/Desktop/tg/yowsup/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.5/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.5/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib/python3.5/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/layers/auth/layer_authentication.py", line 81, in handleFailure
    raise AuthError(nodeEntity.getReason())
yowsup.layers.auth.autherror.AuthError: not-authorized

**Comment by neutrino-01** [comment]
I solve the error and script is running without error but message is not received

**Comment by DanielDPN** [comment]
@shubhamivane  How did you solve this error?

**Comment by neutrino-01** [comment]
this error is automatically solved and my number is banned by whatsapp.

**Comment by sukirtisharma26** [comment]
I got this error when my number was registered again  and I was using old passoword.
Also If you are using the number nowhere else , chances are that it might be blocked. 

Try registering again , you'll know your number's status.
